import { transform } from 'sucrase'
import { instrument } from '@/lib/breakpoints'

export type Peek = { label: string; value: unknown; line?: number }
type RunBase = { logs: string[]; peeks: Peek[] }
export type RunOutcome = ({ ok: true; value: unknown; durationMs: number } & RunBase) | ({ ok: false; phase: 'compile' | 'runtime' | 'timeout'; name: string; message: string } & RunBase)
const TIMEOUT_MS=2000
const MAX_PEEKS=100
const WORKER_SOURCE=`
const format=(v)=>{if(typeof v==='string')return v;if(v===undefined)return 'undefined';if(typeof v==='function')return '[Function]';try{return JSON.stringify(v,null,2)??String(v)}catch{return String(v)}};
const snapshot=(v,seen=new WeakSet(),depth=0)=>{if(typeof v==='function')return '[Function'+(v.name?' '+v.name:'')+']';if(typeof v==='symbol'||typeof v==='bigint')return String(v);if(v===null||typeof v!=='object')return v;if(seen.has(v))return '[Circular]';if(depth>20)return '[…]';seen.add(v);let out;if(Array.isArray(v))out=v.map((x)=>snapshot(x,seen,depth+1));else if(v instanceof Map)out=Object.fromEntries([...v].map(([k,x])=>[String(k),snapshot(x,seen,depth+1)]));else if(v instanceof Set)out=[...v].map((x)=>snapshot(x,seen,depth+1));else if(v instanceof Date)out=v.toISOString();else{out={};for(const k of Object.keys(v))out[k]=snapshot(v[k],seen,depth+1)}seen.delete(v);return out};
self.onmessage=async(event)=>{const{code,A,B}=event.data;const logs=[];const push=(...args)=>{if(logs.length<200)logs.push(args.map(format).join(' '))};const sandboxConsole={log:push,info:push,warn:push,error:push,debug:push,table:push,dir:push};let peekCount=0;const record=(value,label,auto,line)=>{peekCount++;if(peekCount<=${MAX_PEEKS})self.postMessage({type:'peek',peek:{label:label!==undefined?String(label):auto!==undefined?auto:'#'+peekCount,value:snapshot(value),line}});return value};const peek=(value,label)=>record(value,label);const __peekAt=(line,auto)=>(value,label)=>record(value,label,auto,line);const start=performance.now();try{const fn=new Function('A','B','console','peek','__peekAt','"use strict";\\n'+code+'\\n;if (typeof solve !== "function") throw new ReferenceError("Define a function named solve(A, B) that returns C.");\\nreturn solve(A, B);');let value=fn(A,B,sandboxConsole,peek,__peekAt);if(value&&typeof value.then==='function')value=await value;const durationMs=performance.now()-start;try{self.postMessage({type:'done',ok:true,value,logs,durationMs})}catch{self.postMessage({type:'done',ok:false,phase:'runtime',name:'SerializationError',message:'The returned value contains functions or other non-serializable data.',logs})}}catch(error){self.postMessage({type:'done',ok:false,phase:'runtime',name:(error&&error.name)||'Error',message:(error&&error.message)||String(error),logs})}};
`
let workerUrl:string|null=null
function getWorkerUrl(){ if(!workerUrl) workerUrl=URL.createObjectURL(new Blob([WORKER_SOURCE],{type:'text/javascript'})); return workerUrl }
function compile(source:string){ return transform(source,{transforms:['typescript'],disableESTransforms:true}).code }
export function canCompile(source:string){ try { compile(source); return true } catch { return false } }
export function runSolution(source:string,A:unknown,B:unknown,breakpoints:number[]=[]):Promise<RunOutcome>{ let code:string; try{code=compile(source)}catch(error){const err=error as Error; return Promise.resolve({ok:false,phase:'compile',name:'SyntaxError',message:err.message,logs:[],peeks:[]})} try{code=compile(instrument(source,breakpoints))}catch{/* Run without line-tagged peeks rather than fail on our own rewrite. */} return new Promise((resolve)=>{const worker=new Worker(getWorkerUrl());const peeks:Peek[]=[];const timer=window.setTimeout(()=>{worker.terminate();resolve({ok:false,phase:'timeout',name:'Timeout',message:`Execution exceeded ${TIMEOUT_MS/1000}s. Check for infinite loops.`,logs:[],peeks})},TIMEOUT_MS); type WorkerMessage={type:'peek';peek:Peek}|({type:'done'}&Omit<RunOutcome,'peeks'>); worker.onmessage=(event:MessageEvent<WorkerMessage>)=>{const data=event.data;if(data.type==='peek'){peeks.push(data.peek);return}window.clearTimeout(timer);worker.terminate();const{type:_type,...outcome}=data;resolve({...outcome,peeks} as RunOutcome)};worker.onerror=(event)=>{event.preventDefault();window.clearTimeout(timer);worker.terminate();resolve({ok:false,phase:'runtime',name:'Error',message:event.message||'Unknown worker error',logs:[],peeks})};worker.postMessage({code,A,B})}) }
